all: remove dependency on gce repository
Since around 13 December 2025, the gce repository return an error 403,

  error: failed retrieving file 'gce.db' from storage.googleapis.com
   : The requested URL returned error: 403

We then build google-compute-engine and google-guest-agent and host it
under build.kilabit.info repository using the latest releases [1][2].

For google-compute-engine we use version 20251014.00-1.
For google-guest-agent we use version 20251223.00-1.

[1]: https://build.kilabit.info/karajo/app/#job_aur_google-compute-engine
[2]: https://build.kilabit.info/karajo/app/#job_aur_google-guest-agent